### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dieguitoweb** [dieguitoweb/spazi-unimi-android-app#3]
As a user I want to be able to search a particular room/building by room/building name.
The results list could be splitted in two sub-list: buildings and rooms.

**Comment by carlobellettini** [comment]
bello...

chiaramente quando faccio ricerche casuali ogni tanto capita qualcosa di
strano...

cerca

conca

Studio Conca (Livorno)

apre piantina, ma non c'è evidenziata (né traccia) della aula in
questione...

pensi siano tanti questi casi?

Carlo

2015-10-19 15:03 GMT+02:00 Diego <notifications@github.com>:

> Closed #3
> <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#event-439093984>
> .
>



-- 
   ___             _____                         | *Eng. Ph.D. Assoc.Prof.*
  /  _)    /)     (, /  )     /)/)   _/_/_       | *DI*  Univ. of Milan
 /  _  __ (/ __     /--(   _ (/(/ _  / / . _   . | Via Comelico 39/41
(__(_)_)(_/\(_)  ( /____)_(/_/\/\(/_(_(_(_/ )_(_ | I20135 Milan IT
               http://www.di.unimi.it/bellettini | ph. +39(02)50316255

**Comment by dieguitoweb** [comment]
sì ho notato qualche caso anche io.. in Fisica ad esempio Auletta IFGA Fis ( Rialzato Piano Terra ); in questo caso ad esempio la stanza non è presente ( ci sarà la polyline ma non è marcata con l’ID) nella piantina SVG..
È migliorato il caricamento delle piantine? Ho predisposto una cache di 50Mb per alcune richieste HTTP.
Ho preparato anche l’endpoint per gli orari, ad esempio http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/ <http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/>

Diego

Diego Costantino

CdL Informatica
714927
diego.costantino@studenti.unimi.it

**Comment by carlobellettini** [comment]
io non ho avuto più problemi con il caricamento...
stai usando quella libreria che si diceva?

Carlo

Il giorno 19 ottobre 2015 18:29, Diego <notifications@github.com> ha
scritto:

> sì ho notato qualche caso anche io.. in Fisica ad esempio Auletta IFGA Fis
> ( Rialzato Piano Terra ); in questo caso ad esempio la stanza non è
> presente ( ci sarà la polyline ma non è marcata con l’ID) nella piantina
> SVG..
> È migliorato il caricamento delle piantine? Ho predisposto una cache di
> 50Mb per alcune richieste HTTP.
> Ho preparato anche l’endpoint per gli orari, ad esempio
> http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/ <
> http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/>
>
> Diego
>
> Diego Costantino
>
> CdL Informatica
> 714927
> diego.costantino@studenti.unimi.it
>
>
>
>
>
>
> > On 19 Oct 2015, at 18:16, Carlo Bellettini <notifications@github.com>
> wrote:
> >
> > bello...
> >
> > chiaramente quando faccio ricerche casuali ogni tanto capita qualcosa di
> > strano...
> >
> > cerca
> >
> > conca
> >
> > Studio Conca (Livorno)
> >
> > apre piantina, ma non c'è evidenziata (né traccia) della aula in
> > questione...
> >
> > pensi siano tanti questi casi?
> >
> > Carlo
> >
> > 2015-10-19 15:03 GMT+02:00 Diego <notifications@github.com>:
> >
> > > Closed #3
> > > <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#event-439093984
> >
> > > .
> > >
> >
> >
> >
> > --
> > ___ _____ | *Eng. Ph.D. Assoc.Prof.*
> > / _) /) (, / ) /)/) _/_/_ | *DI* Univ. of Milan
> > / _ __ (/ __ /--( _ (/(/ _ / / . _ . | Via Comelico 39/41
> > (__(_)_)(_/\(_) ( /____)_(/_/\/\(/_(_(_(_/ )_(_ | I20135 Milan IT
> > http://www.di.unimi.it/bellettini | ph. +39(02)50316255
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149263657
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149271256>
> .
>



-- 
<table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
align="left" valign="top" width="10"> <p style="padding-right:10px;
font-family:Georgia, Times, serif; font-size:10px; "> <img src="
https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg"
border="0" height="80"> </p> </td> <td align="left"> <p
style="font-family:Georgia, Times, serif; font-size:10px; line-height:12px;
color:rgb(33, 33, 33);"><span style="font-weight:bold;
display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
Professor</span></p> <p style="font-family:Georgia, Times, serif;
font-size:10px; line-height:10px;"> <span style="font-weight:bold;
display:inline;"> Dipartimento di Informatica <br/> Università degli studi
di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39, I-20135
MILANO <br> <a style="text-decoration:none" href="
http://www.di.unimi.it/bellettini"> <img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a> <a
style="text-decoration:none" href="https://twitter.com/carlobellettini">
<img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter"> </a> <a
href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
style="font-family:Georgia, Times, serif; font-size:9px; line-height:12px;"
class="txt signature_disclaimer-target"> <a class="link
signature_website-target sig-hide" href="
http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless"
style="color:rgb(0, 140, 171); text-decoration:none; display:inline;">Why
there is no disclaimer in this email</a> </tr> </tbody> </table>

**Comment by dieguitoweb** [comment]
no, spulciando bene la documentazione ho trovato che la classe HttpURLConnection che usato per le chiamate alle API REST, supporta la cache da Android 4.0 (HttpResponseCache), e ho preferito optare per questa soluzione. Effettivamente sembra migliorato il caricamento delle piantine.. 
Credo possa bastare una cache di 50MB considerando che un SVG di un piano pesa mediamente 3/4MB..
Oggi vorrei integrare gli orari e possibilmente anche la lettura del QRCode per identificare una stanza o un edificio :)


Diego

Diego Costantino

CdL Informatica
714927
diego.costantino@studenti.unimi.it

**Comment by carlobellettini** [comment]
pesa così tanto l'SVG?  sicuro????


Il giorno 20 ottobre 2015 10:07, Diego <notifications@github.com> ha
scritto:

> no, spulciando bene la documentazione ho trovato che la classe
> HttpURLConnection che usato per le chiamate alle API REST, supporta la
> cache da Android 4.0 (HttpResponseCache), e ho preferito optare per questa
> soluzione. Effettivamente sembra migliorato il caricamento delle piantine..
> Credo possa bastare una cache di 50MB considerando che un SVG di un piano
> pesa mediamente 3/4MB..
> Oggi vorrei integrare gli orari e possibilmente anche la lettura del
> QRCode per identificare una stanza o un edificio :)
>
>
> Diego
>
> Diego Costantino
>
> CdL Informatica
> 714927
> diego.costantino@studenti.unimi.it
>
>
>
>
>
>
> > On 19 Oct 2015, at 18:31, Carlo Bellettini <notifications@github.com>
> wrote:
> >
> > io non ho avuto più problemi con il caricamento...
> > stai usando quella libreria che si diceva?
> >
> > Carlo
> >
> > Il giorno 19 ottobre 2015 18:29, Diego <notifications@github.com> ha
> > scritto:
> >
> > > sì ho notato qualche caso anche io.. in Fisica ad esempio Auletta IFGA
> Fis
> > > ( Rialzato Piano Terra ); in questo caso ad esempio la stanza non è
> > > presente ( ci sarà la polyline ma non è marcata con l’ID) nella
> piantina
> > > SVG..
> > > È migliorato il caricamento delle piantine? Ho predisposto una cache di
> > > 50Mb per alcune richieste HTTP.
> > > Ho preparato anche l’endpoint per gli orari, ad esempio
> > > http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/ <
> > > http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/>
> > >
> > > Diego
> > >
> > > Diego Costantino
> > >
> > > CdL Informatica
> > > 714927
> > > diego.costantino@studenti.unimi.it
> > >
> > >
> > >
> > >
> > >
> > >
> > > > On 19 Oct 2015, at 18:16, Carlo Bellettini <notifications@github.com
> >
> > > wrote:
> > > >
> > > > bello...
> > > >
> > > > chiaramente quando faccio ricerche casuali ogni tanto capita
> qualcosa di
> > > > strano...
> > > >
> > > > cerca
> > > >
> > > > conca
> > > >
> > > > Studio Conca (Livorno)
> > > >
> > > > apre piantina, ma non c'è evidenziata (né traccia) della aula in
> > > > questione...
> > > >
> > > > pensi siano tanti questi casi?
> > > >
> > > > Carlo
> > > >
> > > > 2015-10-19 15:03 GMT+02:00 Diego <notifications@github.com>:
> > > >
> > > > > Closed #3
> > > > > <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3>.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#event-439093984
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > ___ _____ | *Eng. Ph.D. Assoc.Prof.*
> > > > / _) /) (, / ) /)/) _/_/_ | *DI* Univ. of Milan
> > > > / _ __ (/ __ /--( _ (/(/ _ / / . _ . | Via Comelico 39/41
> > > > (__(_)_)(_/\(_) ( /____)_(/_/\/\(/_(_(_(_/ )_(_ | I20135 Milan IT
> > > > http://www.di.unimi.it/bellettini | ph. +39(02)50316255
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149263657
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149271256
> >
> > > .
>
> > >
> >
> >
> >
> > --
> > <table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
> > align="left" valign="top" width="10"> <p style="padding-right:10px;
> > font-family:Georgia, Times, serif; font-size:10px; "> <img src="
> >
> https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg
> "
> > border="0" height="80"> </p> </td> <td align="left"> <p
> > style="font-family:Georgia, Times, serif; font-size:10px;
> line-height:12px;
> > color:rgb(33, 33, 33);"><span style="font-weight:bold;
> > display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
> > Professor</span></p> <p style="font-family:Georgia, Times, serif;
> > font-size:10px; line-height:10px;"> <span style="font-weight:bold;
> > display:inline;"> Dipartimento di Informatica <br/> Università degli
> studi
> > di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39, I-20135
> > MILANO <br> <a style="text-decoration:none" href="
> > http://www.di.unimi.it/bellettini"> <img width="16" height="16" src="
> > http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a> <a
> > style="text-decoration:none" href="https://twitter.com/carlobellettini">
> > <img width="16" height="16" src="
> > http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter"> </a> <a
> > href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
> > height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
> > alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
> > style="font-family:Georgia, Times, serif; font-size:9px;
> line-height:12px;"
> > class="txt signature_disclaimer-target"> <a class="link
> > signature_website-target sig-hide" href="
> >
> http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless
> "
> > style="color:rgb(0, 140, 171); text-decoration:none; display:inline;">Why
> > there is no disclaimer in this email</a> </tr> </tbody> </table>
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149272111
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149470124>
> .
>



-- 
<table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
align="left" valign="top" width="10"> <p style="padding-right:10px;
font-family:Georgia, Times, serif; font-size:10px; "> <img src="
https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg"
border="0" height="80"> </p> </td> <td align="left"> <p
style="font-family:Georgia, Times, serif; font-size:10px; line-height:12px;
color:rgb(33, 33, 33);"><span style="font-weight:bold;
display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
Professor</span></p> <p style="font-family:Georgia, Times, serif;
font-size:10px; line-height:10px;"> <span style="font-weight:bold;
display:inline;"> Dipartimento di Informatica <br/> Università degli studi
di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39, I-20135
MILANO <br> <a style="text-decoration:none" href="
http://www.di.unimi.it/bellettini"> <img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a> <a
style="text-decoration:none" href="https://twitter.com/carlobellettini">
<img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter"> </a> <a
href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
style="font-family:Georgia, Times, serif; font-size:9px; line-height:12px;"
class="txt signature_disclaimer-target"> <a class="link
signature_website-target sig-hide" href="
http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless"
style="color:rgb(0, 140, 171); text-decoration:none; display:inline;">Why
there is no disclaimer in this email</a> </tr> </tbody> </table>

**Comment by dieguitoweb** [comment]
No, ops errore.. pesano molto meno! 
Nell’ordine dei 100Kb mi ricordavo pesassero molto di più inizialmente, ma poi li avevamo scalati e ottimizzati :)

Diego Costantino

CdL Informatica
714927
diego.costantino@studenti.unimi.it

**Comment by carlobellettini** [comment]
uhm... essendo svg (quindi vettoriali) ... la scalatura non dovrebbe
influire su dimensione...

boh... mi perdo qualcosa forse?

Il giorno 20 ottobre 2015 10:11, Diego <notifications@github.com> ha
scritto:

> No, ops errore.. pesano molto meno!
> Nell’ordine dei 100Kb mi ricordavo pesassero molto di più inizialmente, ma
> poi li avevamo scalati e ottimizzati :)
>
> Diego Costantino
>
> CdL Informatica
> 714927
> diego.costantino@studenti.unimi.it
>
>
>
>
>
>
> > On 20 Oct 2015, at 10:08, Carlo Bellettini <notifications@github.com>
> wrote:
> >
> > pesa così tanto l'SVG? sicuro????
> >
> >
> > Il giorno 20 ottobre 2015 10:07, Diego <notifications@github.com> ha
> > scritto:
> >
> > > no, spulciando bene la documentazione ho trovato che la classe
> > > HttpURLConnection che usato per le chiamate alle API REST, supporta la
> > > cache da Android 4.0 (HttpResponseCache), e ho preferito optare per
> questa
> > > soluzione. Effettivamente sembra migliorato il caricamento delle
> piantine..
> > > Credo possa bastare una cache di 50MB considerando che un SVG di un
> piano
> > > pesa mediamente 3/4MB..
> > > Oggi vorrei integrare gli orari e possibilmente anche la lettura del
> > > QRCode per identificare una stanza o un edificio :)
> > >
> > >
> > > Diego
> > >
> > > Diego Costantino
> > >
> > > CdL Informatica
> > > 714927
> > > diego.costantino@studenti.unimi.it
> > >
> > >
> > >
> > >
> > >
> > >
> > > > On 19 Oct 2015, at 18:31, Carlo Bellettini <notifications@github.com
> >
> > > wrote:
> > > >
> > > > io non ho avuto più problemi con il caricamento...
> > > > stai usando quella libreria che si diceva?
> > > >
> > > > Carlo
> > > >
> > > > Il giorno 19 ottobre 2015 18:29, Diego <notifications@github.com> ha
> > > > scritto:
> > > >
> > > > > sì ho notato qualche caso anche io.. in Fisica ad esempio Auletta
> IFGA
> > > Fis
> > > > > ( Rialzato Piano Terra ); in questo caso ad esempio la stanza non è
> > > > > presente ( ci sarà la polyline ma non è marcata con l’ID) nella
> > > piantina
> > > > > SVG..
> > > > > È migliorato il caricamento delle piantine? Ho predisposto una
> cache di
> > > > > 50Mb per alcune richieste HTTP.
> > > > > Ho preparato anche l’endpoint per gli orari, ad esempio
> > > > > http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/ <
> > > > > http://127.0.0.1:5000/api/v1.0/rooms/timetable/11020/1052/>
> > > > >
> > > > > Diego
> > > > >
> > > > > Diego Costantino
> > > > >
> > > > > CdL Informatica
> > > > > 714927
> > > > > diego.costantino@studenti.unimi.it
> > > > >
> > > > >
> > > > >
> > > > >
> > > > >
> > > > >
> > > > > > On 19 Oct 2015, at 18:16, Carlo Bellettini <
> notifications@github.com
> > > >
> > > > > wrote:
> > > > > >
> > > > > > bello...
> > > > > >
> > > > > > chiaramente quando faccio ricerche casuali ogni tanto capita
> > > qualcosa di
> > > > > > strano...
> > > > > >
> > > > > > cerca
> > > > > >
> > > > > > conca
> > > > > >
> > > > > > Studio Conca (Livorno)
> > > > > >
> > > > > > apre piantina, ma non c'è evidenziata (né traccia) della aula in
> > > > > > questione...
> > > > > >
> > > > > > pensi siano tanti questi casi?
> > > > > >
> > > > > > Carlo
> > > > > >
> > > > > > 2015-10-19 15:03 GMT+02:00 Diego <notifications@github.com>:
> > > > > >
> > > > > > > Closed #3
> > > > > > > <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3>.
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > >
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#event-439093984
> > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > ___ _____ | *Eng. Ph.D. Assoc.Prof.*
> > > > > > / _) /) (, / ) /)/) _/_/_ | *DI* Univ. of Milan
> > > > > > / _ __ (/ __ /--( _ (/(/ _ / / . _ . | Via Comelico 39/41
> > > > > > (__(_)_)(_/\(_) ( /____)_(/_/\/\(/_(_(_(_/ )_(_ | I20135 Milan IT
> > > > > > http://www.di.unimi.it/bellettini | ph. +39(02)50316255
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub <
> > > > >
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149263657
> > > > > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
>
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149271256
> > > >
> > > > > .
> > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > <table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
> > > > align="left" valign="top" width="10"> <p style="padding-right:10px;
> > > > font-family:Georgia, Times, serif; font-size:10px; "> <img src="
> > > >
> > >
> https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg
> > > "
> > > > border="0" height="80"> </p> </td> <td align="left"> <p
> > > > style="font-family:Georgia, Times, serif; font-size:10px;
> > > line-height:12px;
> > > > color:rgb(33, 33, 33);"><span style="font-weight:bold;
> > > > display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
> > > > Professor</span></p> <p style="font-family:Georgia, Times, serif;
> > > > font-size:10px; line-height:10px;"> <span style="font-weight:bold;
> > > > display:inline;"> Dipartimento di Informatica <br/> Università degli
> > > studi
> > > > di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39,
> I-20135
> > > > MILANO <br> <a style="text-decoration:none" href="
> > > > http://www.di.unimi.it/bellettini"> <img width="16" height="16"
> src="
> > > > http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a>
> <a
> > > > style="text-decoration:none" href="
> https://twitter.com/carlobellettini">
> > > > <img width="16" height="16" src="
> > > > http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter">
> </a> <a
> > > > href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
> > > > height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
> > > > alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
> > > > style="font-family:Georgia, Times, serif; font-size:9px;
> > > line-height:12px;"
> > > > class="txt signature_disclaimer-target"> <a class="link
> > > > signature_website-target sig-hide" href="
> > > >
> > >
> http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless
> > > "
> > > > style="color:rgb(0, 140, 171); text-decoration:none;
> display:inline;">Why
> > > > there is no disclaimer in this email</a> </tr> </tbody> </table>
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149272111
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149470124
> >
>
> > > .
> > >
> >
> >
> >
> > --
> > <table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
> > align="left" valign="top" width="10"> <p style="padding-right:10px;
> > font-family:Georgia, Times, serif; font-size:10px; "> <img src="
> >
> https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg
> "
> > border="0" height="80"> </p> </td> <td align="left"> <p
> > style="font-family:Georgia, Times, serif; font-size:10px;
> line-height:12px;
> > color:rgb(33, 33, 33);"><span style="font-weight:bold;
> > display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
> > Professor</span></p> <p style="font-family:Georgia, Times, serif;
> > font-size:10px; line-height:10px;"> <span style="font-weight:bold;
> > display:inline;"> Dipartimento di Informatica <br/> Università degli
> studi
> > di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39, I-20135
> > MILANO <br> <a style="text-decoration:none" href="
> > http://www.di.unimi.it/bellettini"> <img width="16" height="16" src="
> > http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a> <a
> > style="text-decoration:none" href="https://twitter.com/carlobellettini">
> > <img width="16" height="16" src="
> > http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter"> </a> <a
> > href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
> > height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
> > alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
> > style="font-family:Georgia, Times, serif; font-size:9px;
> line-height:12px;"
> > class="txt signature_disclaimer-target"> <a class="link
> > signature_website-target sig-hide" href="
> >
> http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless
> "
> > style="color:rgb(0, 140, 171); text-decoration:none; display:inline;">Why
> > there is no disclaimer in this email</a> </tr> </tbody> </table>
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149470495
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieguitoweb/spazi-unimi-android-app/issues/3#issuecomment-149471673>
> .
>



-- 
<table width="350" border="0" cellpadding="0"> <tbody> <tr> <td
align="left" valign="top" width="10"> <p style="padding-right:10px;
font-family:Georgia, Times, serif; font-size:10px; "> <img src="
https://en.gravatar.com/userimage/33381074/90cb4867681be5f84cd9adab66d87731.jpeg"
border="0" height="80"> </p> </td> <td align="left"> <p
style="font-family:Georgia, Times, serif; font-size:10px; line-height:12px;
color:rgb(33, 33, 33);"><span style="font-weight:bold;
display:inline;">Carlo Bellettini</span> <span>/ PhD Associate
Professor</span></p> <p style="font-family:Georgia, Times, serif;
font-size:10px; line-height:10px;"> <span style="font-weight:bold;
display:inline;"> Dipartimento di Informatica <br/> Università degli studi
di Milano</span> <br>tel: +39 02 50316255 <br>Via Comelico 39, I-20135
MILANO <br> <a style="text-decoration:none" href="
http://www.di.unimi.it/bellettini"> <img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/home.png" alt="HomePage"> </a> <a
style="text-decoration:none" href="https://twitter.com/carlobellettini">
<img width="16" height="16" src="
http://homes.di.unimi.it/bellettini/twitter.png" alt="Twitter"> </a> <a
href="https://www.linkedin.com/in/carlobellettini"> <img width="16"
height="16" src="http://homes.di.unimi.it/bellettini/linkedin.png"
alt="Linkedin"> </a> </p> </td> </tr> <tr> <td colspan="2"><p
style="font-family:Georgia, Times, serif; font-size:9px; line-height:12px;"
class="txt signature_disclaimer-target"> <a class="link
signature_website-target sig-hide" href="
http://lifehacker.com/5790930/disclaimers-in-email-signatures-are-not-just-annoying-but-legally-meaningless"
style="color:rgb(0, 140, 171); text-decoration:none; display:inline;">Why
there is no disclaimer in this email</a> </tr> </tbody> </table>

**Comment by dieguitoweb** [comment]
scalandoli abbiamo ridotto il numero di cifre decimali usate per le coordinate, e rimosso un po' di metadati inutili :)
